import { Seeder } from 'typeorm-extension';
import { DataSource } from 'typeorm';

import { District } from '@model';

export class DistrictSeeder implements Seeder {
  async run(dataSource: DataSource): Promise<void> {
    const repository = dataSource.getRepository(District);
    const listData: District[] = [
      // Thành phố Hà Nội (30 Districts)
      { codeProvince: "16", code: "001", name: "Quận Ba Đình" },
      { codeProvince: "16", code: "002", name: "Quận Hoàn Kiếm" },
      { codeProvince: "16", code: "003", name: "Quận Tây Hồ" },
      { codeProvince: "16", code: "004", name: "Quận Long Biên" },
      { codeProvince: "16", code: "005", name: "Quận Cầu Giấy" },
      { codeProvince: "16", code: "006", name: "Quận Đống Đa" },
      { codeProvince: "16", code: "007", name: "Quận Hai Bà Trưng" },
      { codeProvince: "16", code: "008", name: "Quận Hoàng Mai" },
      { codeProvince: "16", code: "009", name: "Quận Thanh Xuân" },
      { codeProvince: "16", code: "016", name: "Huyện Sóc Sơn" },
      { codeProvince: "16", code: "017", name: "Huyện Đông Anh" },
      { codeProvince: "16", code: "018", name: "Huyện Gia Lâm" },
      { codeProvince: "16", code: "019", name: "Quận Nam Từ Liêm" },
      { codeProvince: "16", code: "020", name: "Huyện Thanh Trì" },
      { codeProvince: "16", code: "021", name: "Quận Bắc Từ Liêm" },
      { codeProvince: "16", code: "250", name: "Huyện Mê Linh" },
      { codeProvince: "16", code: "268", name: "Quận Hà Đông" },
      { codeProvince: "16", code: "269", name: "Thị xã Sơn Tây" },
      { codeProvince: "16", code: "271", name: "Huyện Ba Vì" },
      { codeProvince: "16", code: "272", name: "Huyện Phúc Thọ" },
      { codeProvince: "16", code: "273", name: "Huyện Đan Phượng" },
      { codeProvince: "16", code: "274", name: "Huyện Hoài Đức" },
      { codeProvince: "16", code: "275", name: "Huyện Quốc Oai" },
      { codeProvince: "16", code: "276", name: "Huyện Thạch Thất" },
      { codeProvince: "16", code: "277", name: "Huyện Chương Mỹ" },
      { codeProvince: "16", code: "278", name: "Huyện Thanh Oai" },
      { codeProvince: "16", code: "279", name: "Huyện Thường Tín" },
      { codeProvince: "16", code: "280", name: "Huyện Phú Xuyên" },
      { codeProvince: "16", code: "281", name: "Huyện Ứng Hòa" },
      { codeProvince: "16", code: "282", name: "Huyện Mỹ Đức" },

      // Tỉnh Hà Giang (33 Districts)
      { codeProvince: "18", code: "024", name: "Thành phố Hà Giang" },
      { codeProvince: "18", code: "026", name: "Huyện Đồng Văn" },
      { codeProvince: "18", code: "027", name: "Huyện Mèo Vạc" },
      { codeProvince: "18", code: "028", name: "Huyện Yên Minh" },
      { codeProvince: "18", code: "029", name: "Huyện Quản Bạ" },
      { codeProvince: "18", code: "030", name: "Huyện Vị Xuyên" },
      { codeProvince: "18", code: "031", name: "Huyện Bắc Mê" },
      { codeProvince: "18", code: "032", name: "Huyện Hoàng Su Phì" },
      { codeProvince: "18", code: "033", name: "Huyện Xín Mần" },
      { codeProvince: "18", code: "034", name: "Huyện Bắc Quang" },
      { codeProvince: "18", code: "035", name: "Huyện Quang Bình" },

      // Tỉnh Cao Bằng (33 Districts)
      { codeProvince: "22", code: "040", name: "Thành phố Cao Bằng" },
      { codeProvince: "22", code: "042", name: "Huyện Bảo Lâm" },
      { codeProvince: "22", code: "043", name: "Huyện Bảo Lạc" },
      { codeProvince: "22", code: "045", name: "Huyện Hà Quảng" },
      { codeProvince: "22", code: "047", name: "Huyện Trùng Khánh" },
      { codeProvince: "22", code: "048", name: "Huyện Hạ Lang" },
      { codeProvince: "22", code: "049", name: "Huyện Quảng Hòa" },
      { codeProvince: "22", code: "051", name: "Huyện Hoà An" },
      { codeProvince: "22", code: "052", name: "Huyện Nguyên Bình" },
      { codeProvince: "22", code: "053", name: "Huyện Thạch An" },
      
      // Tỉnh Bắc Kạn (8 Districts)
      { codeProvince: "28", code: "058", name: "Thành Phố Bắc Kạn" },
      { codeProvince: "28", code: "060", name: "Huyện Pác Nặm" },
      { codeProvince: "28", code: "061", name: "Huyện Ba Bể" },
      { codeProvince: "28", code: "062", name: "Huyện Ngân Sơn" },
      { codeProvince: "28", code: "063", name: "Huyện Bạch Thông" },
      { codeProvince: "28", code: "064", name: "Huyện Chợ Đồn" },
      { codeProvince: "28", code: "065", name: "Huyện Chợ Mới" },
      { codeProvince: "28", code: "066", name: "Huyện Na Rì" },

      // Tỉnh Tuyên Quang (7 Districts)
      { codeProvince: "17", code: "071", name: "Thành phố Tuyên Quang" },
      { codeProvince: "17", code: "071", name: "Huyện Lâm Bình" },
      { codeProvince: "17", code: "072", name: "Huyện Na Hang" },
      { codeProvince: "17", code: "073", name: "Huyện Chiêm Hóa" },
      { codeProvince: "17", code: "074", name: "Huyện Hàm Yên" },
      { codeProvince: "17", code: "075", name: "Huyện Yên Sơn" },
      { codeProvince: "17", code: "076", name: "Huyện Sơn Dương" },

      // Tỉnh Lào Cai (9 Districts)
      { codeProvince: "16", code: "080", name: "Thành phố Lào Cai" },
      { codeProvince: "16", code: "082", name: "Huyện Bát Xát" },
      { codeProvince: "16", code: "083", name: "Huyện Mường Khương" },
      { codeProvince: "16", code: "084", name: "Huyện Si Ma Cai" },
      { codeProvince: "16", code: "085", name: "Huyện Bắc Hà" },
      { codeProvince: "16", code: "086", name: "Huyện Bảo Thắng" },
      { codeProvince: "16", code: "087", name: "Huyện Bảo Yên" },
      { codeProvince: "16", code: "088", name: "Thị xã Sa Pa" },
      { codeProvince: "16", code: "089", name: "Huyện Văn Bàn" },
 
      // Tỉnh Điện Biên (10 Districts)
      { codeProvince: "16", code: "094", name: "Thành phố Điện Biên Phủ" },
      { codeProvince: "16", code: "095", name: "Thị Xã Mường Lay" },
      { codeProvince: "16", code: "096", name: "Huyện Mường Nhé" },
      { codeProvince: "16", code: "097", name: "Huyện Mường Chà" },
      { codeProvince: "16", code: "098", name: "Huyện Tủa Chùa" },
      { codeProvince: "16", code: "099", name: "Huyện Tuần Giáo" },
      { codeProvince: "16", code: "100", name: "Huyện Điện Biên" },
      { codeProvince: "16", code: "101", name: "Huyện Điện Biên Đông" },
      { codeProvince: "16", code: "102", name: "Huyện Mường Ảng" },
      { codeProvince: "16", code: "103", name: "Huyện Nậm Pồ" },

      // Tỉnh Lai Châu (8 Districts)
      { codeProvince: "39", code: "105", name: "Thành phố Lai Châu" },
      { codeProvince: "39", code: "106", name: "Huyện Tam Đường" },
      { codeProvince: "39", code: "107", name: "Huyện Mường Tè" },
      { codeProvince: "39", code: "108", name: "Huyện Sìn Hồ" },
      { codeProvince: "39", code: "109", name: "Huyện Phong Thổ" },
      { codeProvince: "39", code: "110", name: "Huyện Than Uyên" },
      { codeProvince: "39", code: "111", name: "Huyện Tân Uyên" },
      { codeProvince: "39", code: "112", name: "Huyện Nậm Nhùn" },

      // Tỉnh Sơn La (12 Districts)
      { codeProvince: "42", code: "116", name: "Thành phố Sơn La" },
      { codeProvince: "42", code: "118", name: "Huyện Quỳnh Nhai" },
      { codeProvince: "42", code: "119", name: "Huyện Thuận Châu" },
      { codeProvince: "42", code: "120", name: "Huyện Mường La" },
      { codeProvince: "42", code: "121", name: "Huyện Bắc Yên" },
      { codeProvince: "42", code: "122", name: "Huyện Phù Yên" },
      { codeProvince: "42", code: "123", name: "Huyện Mộc Châu" },
      { codeProvince: "42", code: "124", name: "Huyện Yên Châu" },
      { codeProvince: "42", code: "125", name: "Huyện Mai Sơn" },
      { codeProvince: "42", code: "126", name: "Huyện Sông Mã" },
      { codeProvince: "42", code: "127", name: "Huyện Sốp Cộp" },
      { codeProvince: "42", code: "128", name: "Huyện Vân Hồ" },

      // Tỉnh Yên Bái (9 Districts)
      { codeProvince: "32", code: "132", name: "Thành phố Yên Bái" },
      { codeProvince: "32", code: "133", name: "Thị xã Nghĩa Lộ" },
      { codeProvince: "32", code: "135", name: "Huyện Lục Yên" },
      { codeProvince: "32", code: "136", name: "Huyện Văn Yên" },
      { codeProvince: "32", code: "137", name: "Huyện Mù Căng Chải" },
      { codeProvince: "32", code: "138", name: "Huyện Trấn Yên" },
      { codeProvince: "32", code: "139", name: "Huyện Trạm Tấu" },
      { codeProvince: "32", code: "140", name: "Huyện Văn Chấn" },
      { codeProvince: "32", code: "141", name: "Huyện Yên Bình" },

      // Tỉnh Hòa Bình (10 Districts)
      { codeProvince: "40", code: "148", name: "Thành phố Hòa Bình" },
      { codeProvince: "40", code: "150", name: "Huyện Đà Bắc" },
      { codeProvince: "40", code: "152", name: "Huyện Lương Sơn" },
      { codeProvince: "40", code: "153", name: "Huyện Kim Bôi" },
      { codeProvince: "40", code: "154", name: "Huyện Cao Phong" },
      { codeProvince: "40", code: "155", name: "Huyện Tân Lạc" },
      { codeProvince: "40", code: "156", name: "Huyện Mai Châu" },
      { codeProvince: "40", code: "157", name: "Huyện Lạc Sơn" },
      { codeProvince: "40", code: "158", name: "Huyện Yên Thủy" },
      { codeProvince: "40", code: "159", name: "Huyện Lạc Thủy" },

      // Tỉnh Thái Nguyên (9 Districts)
      { codeProvince: "25", code: "164", name: "Thành phố Thái Nguyên" },
      { codeProvince: "25", code: "165", name: "Thành phố Sông Công" },
      { codeProvince: "25", code: "167", name: "Huyện Định Hóa" },
      { codeProvince: "25", code: "168", name: "Huyện Phú Lương" },
      { codeProvince: "25", code: "169", name: "Huyện Đồng Hỷ" },
      { codeProvince: "25", code: "170", name: "Huyện Võ Nhai" },
      { codeProvince: "25", code: "171", name: "Huyện Đại Từ" },
      { codeProvince: "25", code: "172", name: "Thành phố Phổ Yên" },
      { codeProvince: "25", code: "173", name: "Huyện Phú Bình" },

      // Tỉnh Lạng Sơn (11 Districts)
      { codeProvince: "23", code: "178", name: "Thành phố Lạng Sơn" },
      { codeProvince: "23", code: "180", name: "Huyện Tràng Định" },
      { codeProvince: "23", code: "181", name: "Huyện Bình Gia" },
      { codeProvince: "23", code: "182", name: "Huyện Văn Lãng" },
      { codeProvince: "23", code: "183", name: "Huyện Cao Lộc" },
      { codeProvince: "23", code: "184", name: "Huyện Văn Quan" },
      { codeProvince: "23", code: "185", name: "Huyện Bắc Sơn" },
      { codeProvince: "23", code: "186", name: "Huyện Hữu Lũng" },
      { codeProvince: "23", code: "187", name: "Huyện Chi Lăng" },
      { codeProvince: "23", code: "188", name: "Huyện Lộc Bình" },
      { codeProvince: "23", code: "189", name: "Huyện Đình Lập" },

      // Tỉnh Quảng Ninh (13 Districts)
      { codeProvince: "20", code: "193", name: "Thành phố Hạ Long" },
      { codeProvince: "20", code: "194", name: "Thành phố Móng Cái" },
      { codeProvince: "20", code: "195", name: "Thành phố Cẩm Phả" },
      { codeProvince: "20", code: "196", name: "Thành phố Uông Bí" },
      { codeProvince: "20", code: "198", name: "Huyện Bình Liêu" },
      { codeProvince: "20", code: "199", name: "Huyện Tiên Yên" },
      { codeProvince: "20", code: "200", name: "Huyện Đầm Hà" },
      { codeProvince: "20", code: "201", name: "Huyện Hải Hà" },
      { codeProvince: "20", code: "202", name: "Huyện Ba Chẽ" },
      { codeProvince: "20", code: "203", name: "Huyện Vân Đồn" },
      { codeProvince: "20", code: "205", name: "Thị xã Đông Triều" },
      { codeProvince: "20", code: "206", name: "Thị xã Quảng Yên" },
      { codeProvince: "20", code: "207", name: "Huyện Cô Tô" },

      // Tỉnh Bắc Giang (10 Districts)
      { codeProvince: "23", code: "213", name: "Thành phố Bắc Giang" },
      { codeProvince: "23", code: "215", name: "Huyện Yên Thế" },
      { codeProvince: "23", code: "216", name: "Huyện Tân Yên" },
      { codeProvince: "23", code: "217", name: "Huyện Lạng Giang" },
      { codeProvince: "23", code: "218", name: "Huyện Lục Nam" },
      { codeProvince: "23", code: "219", name: "Huyện Lục Ngạn" },
      { codeProvince: "23", code: "220", name: "Huyện Sơn Động" },
      { codeProvince: "23", code: "221", name: "Huyện Yên Dũng" },
      { codeProvince: "23", code: "222", name: "Huyện Việt Yên" },
      { codeProvince: "23", code: "223", name: "Huyện Hiệp Hòa" },

      // Tỉnh Phú Thọ (13 Districts)
      { codeProvince: "40", code: "227", name: "Thành phố Việt Trì" },
      { codeProvince: "40", code: "228", name: "Thị xã Phú Thọ" },
      { codeProvince: "40", code: "230", name: "Huyện Đoan Hùng" },
      { codeProvince: "40", code: "231", name: "Huyện Hạ Hoà" },
      { codeProvince: "40", code: "232", name: "Huyện Thanh Ba" },
      { codeProvince: "40", code: "233", name: "Huyện Phù Ninh" },
      { codeProvince: "40", code: "234", name: "Huyện Yên Lập" },
      { codeProvince: "40", code: "235", name: "Huyện Cẩm Khê" },
      { codeProvince: "40", code: "236", name: "Huyện Tam Nông" },
      { codeProvince: "40", code: "237", name: "Huyện Lâm Thao" },
      { codeProvince: "40", code: "238", name: "Huyện Thanh Sơn" },
      { codeProvince: "40", code: "239", name: "Huyện Thanh Thuỷ" },
      { codeProvince: "40", code: "240", name: "Huyện Tân Sơn" },

      // Tỉnh Vĩnh Phúc (9 Districts)
      { codeProvince: "28", code: "243", name: "Thành phố Vĩnh Yên" },
      { codeProvince: "28", code: "244", name: "Thành phố Phúc Yên" },
      { codeProvince: "28", code: "246", name: "Huyện Lập Thạch" },
      { codeProvince: "28", code: "247", name: "Huyện Tam Dương" },
      { codeProvince: "28", code: "248", name: "Huyện Tam Đảo" },
      { codeProvince: "28", code: "249", name: "Huyện Bình Xuyên" },
      { codeProvince: "28", code: "251", name: "Huyện Yên Lạc" },
      { codeProvince: "28", code: "252", name: "Huyện Vĩnh Tường" },
      { codeProvince: "28", code: "253", name: "Huyện Sông Lô" },

      // Tỉnh Bắc Ninh (8 Districts)
      { codeProvince: "22", code: "256", name: "Thành phố Bắc Ninh" },
      { codeProvince: "22", code: "258", name: "Huyện Yên Phong" },
      { codeProvince: "22", code: "259", name: "Thị xã Quế Võ" },
      { codeProvince: "22", code: "260", name: "Huyện Tiên Du" },
      { codeProvince: "22", code: "261", name: "Thành phố Từ Sơn" },
      { codeProvince: "22", code: "262", name: "Thị xã Thuận Thành" },
      { codeProvince: "22", code: "263", name: "Huyện Gia Bình" },
      { codeProvince: "22", code: "264", name: "Huyện Lương Tài" },

      // Tỉnh Hải Dương (12 Districts)
      { codeProvince: "17", code: "288", name: "Thành phố Hải Dương" },
      { codeProvince: "17", code: "290", name: "Thành phố Chí Linh" },
      { codeProvince: "17", code: "291", name: "Huyện Nam Sách" },
      { codeProvince: "17", code: "292", name: "Thị xã Kinh Môn" },
      { codeProvince: "17", code: "293", name: "Huyện Kim Thành" },
      { codeProvince: "17", code: "294", name: "Huyện Thanh Hà" },
      { codeProvince: "17", code: "295", name: "Huyện Cẩm Giàng" },
      { codeProvince: "17", code: "296", name: "Huyện Bình Giang" },
      { codeProvince: "17", code: "297", name: "Huyện Gia Lộc" },
      { codeProvince: "17", code: "298", name: "Huyện Tứ Kỳ" },
      { codeProvince: "17", code: "299", name: "Huyện Ninh Giang" },
      { codeProvince: "17", code: "300", name: "Huyện Thanh Miện" },

      // Thành phố Hải Phòng (15 Districts)
      { codeProvince: "18", code: "303", name: "Quận Hồng Bàng" },
      { codeProvince: "18", code: "304", name: "Quận Ngô Quyền" },
      { codeProvince: "18", code: "305", name: "Quận Lê Chân" },
      { codeProvince: "18", code: "306", name: "Quận Hải An" },
      { codeProvince: "18", code: "307", name: "Quận Kiến An" },
      { codeProvince: "18", code: "308", name: "Quận Đồ Sơn" },
      { codeProvince: "18", code: "309", name: "Quận Dương Kinh" },
      { codeProvince: "18", code: "311", name: "Huyện Thuỷ Nguyên" },
      { codeProvince: "18", code: "312", name: "Huyện An Dương" },
      { codeProvince: "18", code: "313", name: "Huyện An Lão" },
      { codeProvince: "18", code: "314", name: "Huyện Kiến Thuỵ" },
      { codeProvince: "18", code: "315", name: "Huyện Tiên Lãng" },
      { codeProvince: "18", code: "316", name: "Huyện Vĩnh Bảo" },
      { codeProvince: "18", code: "317", name: "Huyện Cát Hải" },
      { codeProvince: "18", code: "318", name: "Huyện Bạch Long Vĩ" },

      // Tỉnh Hưng Yên (10 Districts)
      { codeProvince: "16", code: "323", name: "Thành phố Hưng Yên" },
      { codeProvince: "16", code: "325", name: "Huyện Văn Lâm" },
      { codeProvince: "16", code: "326", name: "Huyện Văn Giang" },
      { codeProvince: "16", code: "327", name: "Huyện Yên Mỹ" },
      { codeProvince: "16", code: "328", name: "Thị xã Mỹ Hào" },
      { codeProvince: "16", code: "329", name: "Huyện Ân Thi" },
      { codeProvince: "16", code: "330", name: "Huyện Khoái Châu" },
      { codeProvince: "16", code: "331", name: "Huyện Kim Động" },
      { codeProvince: "16", code: "332", name: "Huyện Tiên Lữ" },
      { codeProvince: "16", code: "333", name: "Huyện Phù Cừ" },

      // Tỉnh Thái Bình (8 Districts)
      { codeProvince: "41", code: "336", name: "Thành phố Thái Bình" },
      { codeProvince: "41", code: "338", name: "Huyện Quỳnh Phụ" },
      { codeProvince: "41", code: "339", name: "Huyện Hưng Hà" },
      { codeProvince: "41", code: "340", name: "Huyện Đông Hưng" },
      { codeProvince: "41", code: "341", name: "Huyện Thái Thụy" },
      { codeProvince: "41", code: "342", name: "Huyện Tiền Hải" },
      { codeProvince: "41", code: "343", name: "Huyện Kiến Xương" },
      { codeProvince: "41", code: "344", name: "Huyện Vũ Thư" },

      // Tỉnh Hà Nam (6 Districts)
      { codeProvince: "40", code: "347", name: "Thành phố Phủ Lý" },
      { codeProvince: "40", code: "349", name: "Thị xã Duy Tiên" },
      { codeProvince: "40", code: "350", name: "Huyện Kim Bảng" },
      { codeProvince: "40", code: "351", name: "Huyện Thanh Liêm" },
      { codeProvince: "40", code: "352", name: "Huyện Bình Lục" },
      { codeProvince: "40", code: "353", name: "Huyện Lý Nhân" },

      // Tỉnh Nam Định (10 Districts)
      { codeProvince: "42", code: "356", name: "Thành phố Nam Định" },
      { codeProvince: "42", code: "358", name: "Huyện Mỹ Lộc" },
      { codeProvince: "42", code: "359", name: "Huyện Vụ Bản" },
      { codeProvince: "42", code: "360", name: "Huyện Ý Yên" },
      { codeProvince: "42", code: "361", name: "Huyện Nghĩa Hưng" },
      { codeProvince: "42", code: "362", name: "Huyện Nam Trực" },
      { codeProvince: "42", code: "363", name: "Huyện Trực Ninh" },
      { codeProvince: "42", code: "364", name: "Huyện Xuân Trường" },
      { codeProvince: "42", code: "365", name: "Huyện Giao Thủy" },
      { codeProvince: "42", code: "366", name: "Huyện Hải Hậu" },

      // Tỉnh Ninh Bình (8 Districts)
      { codeProvince: "43", code: "369", name: "Thành phố Ninh Bình" },
      { codeProvince: "43", code: "370", name: "Thành phố Tam Điệp" },
      { codeProvince: "43", code: "372", name: "Huyện Nho Quan" },
      { codeProvince: "43", code: "373", name: "Huyện Gia Viễn" },
      { codeProvince: "43", code: "374", name: "Huyện Hoa Lư" },
      { codeProvince: "43", code: "375", name: "Huyện Yên Khánh" },
      { codeProvince: "43", code: "376", name: "Huyện Kim Sơn" },
      { codeProvince: "43", code: "377", name: "Huyện Yên Mô" },

      // Tỉnh Thanh Hóa (27 Districts)
      { codeProvince: "44", code: "380", name: "Thành phố Thanh Hóa" },
      { codeProvince: "44", code: "381", name: "Thị xã Bỉm Sơn" },
      { codeProvince: "44", code: "382", name: "Thành phố Sầm Sơn" },
      { codeProvince: "44", code: "384", name: "Huyện Mường Lát" },
      { codeProvince: "44", code: "385", name: "Huyện Quan Hóa" },
      { codeProvince: "44", code: "386", name: "Huyện Bá Thước" },
      { codeProvince: "44", code: "387", name: "Huyện Quan Sơn" },
      { codeProvince: "44", code: "388", name: "Huyện Lang Chánh" },
      { codeProvince: "44", code: "389", name: "Huyện Ngọc Lặc" },
      { codeProvince: "44", code: "390", name: "Huyện Cẩm Thủy" },
      { codeProvince: "44", code: "391", name: "Huyện Thạch Thành" },
      { codeProvince: "44", code: "392", name: "Huyện Hà Trung" },
      { codeProvince: "44", code: "393", name: "Huyện Vĩnh Lộc" },
      { codeProvince: "44", code: "394", name: "Huyện Yên Định" },
      { codeProvince: "44", code: "395", name: "Huyện Thọ Xuân" },
      { codeProvince: "44", code: "396", name: "Huyện Thường Xuân" },
      { codeProvince: "44", code: "397", name: "Huyện Triệu Sơn" },
      { codeProvince: "44", code: "398", name: "Huyện Thiệu Hóa" },
      { codeProvince: "44", code: "399", name: "Huyện Hoằng Hóa" },
      { codeProvince: "44", code: "400", name: "Huyện Hậu Lộc" },
      { codeProvince: "44", code: "401", name: "Huyện Nga Sơn" },
      { codeProvince: "44", code: "402", name: "Huyện Như Xuân" },
      { codeProvince: "44", code: "403", name: "Huyện Như Thanh" },
      { codeProvince: "44", code: "404", name: "Huyện Nông Cống" },
      { codeProvince: "44", code: "405", name: "Huyện Đông Sơn" },
      { codeProvince: "44", code: "406", name: "Huyện Quảng Xương" },
      { codeProvince: "44", code: "407", name: "Thị xã Nghi Sơn" },

      // Thành phố Nghệ An (21 Districts)
      { codeProvince: "46", code: "412", name: "Thành phố Vinh" },
      { codeProvince: "46", code: "413", name: "Thị xã Cửa Lò" },
      { codeProvince: "46", code: "414", name: "Thị xã Thái Hoà" },
      { codeProvince: "46", code: "415", name: "Huyện Quế Phong" },
      { codeProvince: "46", code: "416", name: "Huyện Quỳ Châu" },
      { codeProvince: "46", code: "417", name: "Huyện Kỳ Sơn" },
      { codeProvince: "46", code: "418", name: "Huyện Tương Dương" },
      { codeProvince: "46", code: "419", name: "Huyện Nghĩa Đàn" },
      { codeProvince: "46", code: "420", name: "Huyện Quỳ Hợp" },
      { codeProvince: "46", code: "421", name: "Huyện Quỳnh Lưu" },
      { codeProvince: "46", code: "422", name: "Huyện Con Cuông" },
      { codeProvince: "46", code: "423", name: "Huyện Tân Kỳ" },
      { codeProvince: "46", code: "424", name: "Huyện Anh Sơn" },
      { codeProvince: "46", code: "425", name: "Huyện Diễn Châu" },
      { codeProvince: "46", code: "426", name: "Huyện Yên Thành" },
      { codeProvince: "46", code: "427", name: "Huyện Đô Lương" },
      { codeProvince: "46", code: "428", name: "Huyện Thanh Chương" },
      { codeProvince: "46", code: "429", name: "Huyện Nghi Lộc" },
      { codeProvince: "46", code: "430", name: "Huyện Nam Đàn" },
      { codeProvince: "46", code: "431", name: "Huyện Hưng Nguyên" },
      { codeProvince: "46", code: "432", name: "Thị xã Hoàng Mai" },

      // Tỉnh Hà Tĩnh (13 Districts)
      { codeProvince: "48", code: "436", name: "Thành phố Hà Tĩnh" },
      { codeProvince: "48", code: "437", name: "Thị xã Hồng Lĩnh" },
      { codeProvince: "48", code: "439", name: "Huyện Hương Sơn" },
      { codeProvince: "48", code: "440", name: "Huyện Đức Thọ" },
      { codeProvince: "48", code: "441", name: "Huyện Vũ Quang" },
      { codeProvince: "48", code: "442", name: "Huyện Nghi Xuân" },
      { codeProvince: "48", code: "443", name: "Huyện Can Lộc" },
      { codeProvince: "48", code: "444", name: "Huyện Hương Khê" },
      { codeProvince: "48", code: "445", name: "Huyện Thạch Hà" },
      { codeProvince: "48", code: "446", name: "Huyện Cẩm Xuyên" },
      { codeProvince: "48", code: "447", name: "Huyện Kỳ Anh" },
      { codeProvince: "48", code: "448", name: "Huyện Lộc Hà" },
      { codeProvince: "48", code: "449", name: "Thị xã Kỳ Anh" },

      // Thành phố Quảng Bình (8 Districts)
      { codeProvince: "51", code: "450", name: "Thành Phố Đồng Hới" },
      { codeProvince: "51", code: "452", name: "Huyện Minh Hóa" },
      { codeProvince: "51", code: "453", name: "Huyện Tuyên Hóa" },
      { codeProvince: "51", code: "454", name: "Huyện Quảng Trạch" },
      { codeProvince: "51", code: "455", name: "Huyện Bố Trạch" },
      { codeProvince: "51", code: "456", name: "Huyện Quảng Ninh" },
      { codeProvince: "51", code: "457", name: "Huyện Lệ Thủy" },
      { codeProvince: "51", code: "458", name: "Thị xã Ba Đồn" },

      // Tỉnh Quảng Trị (10 Districts)
      { codeProvince: "52", code: "461", name: "Thành phố Đông Hà" },
      { codeProvince: "52", code: "462", name: "Thị xã Quảng Trị" },
      { codeProvince: "52", code: "464", name: "Huyện Vĩnh Linh" },
      { codeProvince: "52", code: "465", name: "Huyện Hướng Hóa" },
      { codeProvince: "52", code: "466", name: "Huyện Gio Linh" },
      { codeProvince: "52", code: "467", name: "Huyện Đa Krông" },
      { codeProvince: "52", code: "468", name: "Huyện Cam Lộ" },
      { codeProvince: "52", code: "469", name: "Huyện Triệu Phong" },
      { codeProvince: "52", code: "470", name: "Huyện Hải Lăng" },
      { codeProvince: "52", code: "471", name: "Huyện Cồn Cỏ" },

      // Tỉnh Thừa Thiên Huế (9 Districts)
      { codeProvince: "53", code: "474", name: "Thành phố Huế" },
      { codeProvince: "53", code: "476", name: "Huyện Phong Điền" },
      { codeProvince: "53", code: "477", name: "Huyện Quảng Điền" },
      { codeProvince: "53", code: "478", name: "Huyện Phú Vang" },
      { codeProvince: "53", code: "479", name: "Thị xã Hương Thủy" },
      { codeProvince: "53", code: "480", name: "Thị xã Hương Trà" },
      { codeProvince: "53", code: "481", name: "Huyện A Lưới" },
      { codeProvince: "53", code: "482", name: "Huyện Phú Lộc" },
      { codeProvince: "53", code: "483", name: "Huyện Nam Đông" },

      // Thành phố Đà Nẵng (8 Districts)
      { codeProvince: "55", code: "490", name: "Quận Liên Chiểu" },
      { codeProvince: "55", code: "491", name: "Quận Thanh Khê" },
      { codeProvince: "55", code: "492", name: "Quận Hải Châu" },
      { codeProvince: "55", code: "493", name: "Quận Sơn Trà" },
      { codeProvince: "55", code: "494", name: "Quận Ngũ Hành Sơn" },
      { codeProvince: "55", code: "495", name: "Quận Cẩm Lệ" },
      { codeProvince: "55", code: "497", name: "Huyện Hòa Vang" },
      { codeProvince: "55", code: "498", name: "Huyện Hoàng Sa" },

      // Tỉnh Quảng Nam (18 Districts)
      { codeProvince: "56", code: "502", name: "Thành phố Tam Kỳ" },
      { codeProvince: "56", code: "503", name: "Thành phố Hội An" },
      { codeProvince: "56", code: "504", name: "Huyện Tây Giang" },
      { codeProvince: "56", code: "505", name: "Huyện Đông Giang" },
      { codeProvince: "56", code: "506", name: "Huyện Đại Lộc" },
      { codeProvince: "56", code: "507", name: "Thị xã Điện Bàn" },
      { codeProvince: "56", code: "508", name: "Huyện Duy Xuyên" },
      { codeProvince: "56", code: "509", name: "Huyện Quế Sơn" },
      { codeProvince: "56", code: "510", name: "Huyện Nam Giang" },
      { codeProvince: "56", code: "511", name: "Huyện Phước Sơn" },
      { codeProvince: "56", code: "512", name: "Huyện Hiệp Đức" },
      { codeProvince: "56", code: "513", name: "Huyện Thăng Bình" },
      { codeProvince: "56", code: "514", name: "Huyện Tiên Phước" },
      { codeProvince: "56", code: "515", name: "Huyện Bắc Trà My" },
      { codeProvince: "56", code: "516", name: "Huyện Nam Trà My" },
      { codeProvince: "56", code: "517", name: "Huyện Núi Thành" },
      { codeProvince: "56", code: "518", name: "Huyện Phú Ninh" },
      { codeProvince: "56", code: "519", name: "Huyện Nông Sơn" },

      // Tỉnh Quảng Ngãi (13 Districts)
      { codeProvince: "57", code: "522", name: "Thành phố Quảng Ngãi" },
      { codeProvince: "57", code: "524", name: "Huyện Bình Sơn" },
      { codeProvince: "57", code: "525", name: "Huyện Trà Bồng" },
      { codeProvince: "57", code: "527", name: "Huyện Sơn Tịnh" },
      { codeProvince: "57", code: "528", name: "Huyện Tư Nghĩa" },
      { codeProvince: "57", code: "529", name: "Huyện Sơn Hà" },
      { codeProvince: "57", code: "530", name: "Huyện Sơn Tây" },
      { codeProvince: "57", code: "531", name: "Huyện Minh Long" },
      { codeProvince: "57", code: "532", name: "Huyện Nghĩa Hành" },
      { codeProvince: "57", code: "533", name: "Huyện Mộ Đức" },
      { codeProvince: "57", code: "534", name: "Thị xã Đức Phổ" },
      { codeProvince: "57", code: "535", name: "Huyện Ba Tơ" },
      { codeProvince: "57", code: "536", name: "Huyện Lý Sơn" },

      // Tỉnh Bình Định (11 Districts)
      { codeProvince: "59", code: "540", name: "Thành phố Quy Nhơn" },
      { codeProvince: "59", code: "542", name: "Huyện An Lão" },
      { codeProvince: "59", code: "543", name: "Thị xã Hoài Nhơn" },
      { codeProvince: "59", code: "544", name: "Huyện Hoài Ân" },
      { codeProvince: "59", code: "545", name: "Huyện Phù Mỹ" },
      { codeProvince: "59", code: "546", name: "Huyện Vĩnh Thạnh" },
      { codeProvince: "59", code: "547", name: "Huyện Tây Sơn" },
      { codeProvince: "59", code: "548", name: "Huyện Phù Cát" },
      { codeProvince: "59", code: "549", name: "Thị xã An Nhơn" },
      { codeProvince: "59", code: "550", name: "Huyện Tuy Phước" },
      { codeProvince: "59", code: "551", name: "Huyện Vân Canh" },

      // Tỉnh Phú Yên (9 Districts)
      { codeProvince: "62", code: "555", name: "Thành phố Tuy Hoà" },
      { codeProvince: "62", code: "557", name: "Thị xã Sông Cầu" },
      { codeProvince: "62", code: "558", name: "Huyện Đồng Xuân" },
      { codeProvince: "62", code: "559", name: "Huyện Tuy An" },
      { codeProvince: "62", code: "560", name: "Huyện Sơn Hòa" },
      { codeProvince: "62", code: "561", name: "Huyện Sông Hinh" },
      { codeProvince: "62", code: "562", name: "Huyện Tây Hoà" },
      { codeProvince: "62", code: "563", name: "Huyện Phú Hoà" },
      { codeProvince: "62", code: "564", name: "Thị xã Đông Hòa" },

      // Tỉnh Khánh Hòa (9 Districts)
      { codeProvince: "65", code: "568", name: "Thành phố Nha Trang" },
      { codeProvince: "65", code: "569", name: "Thành phố Cam Ranh" },
      { codeProvince: "65", code: "570", name: "Huyện Cam Lâm" },
      { codeProvince: "65", code: "571", name: "Huyện Vạn Ninh" },
      { codeProvince: "65", code: "572", name: "Thị xã Ninh Hòa" },
      { codeProvince: "65", code: "573", name: "Huyện Khánh Vĩnh" },
      { codeProvince: "65", code: "574", name: "Huyện Diên Khánh" },
      { codeProvince: "65", code: "575", name: "Huyện Khánh Sơn" },
      { codeProvince: "65", code: "576", name: "Huyện Trường Sa" },

      // Tỉnh Ninh Thuận (7 Districts)
      { codeProvince: "66", code: "582", name: "Thành phố Phan Rang-Tháp Chàm" },
      { codeProvince: "66", code: "584", name: "Huyện Bác Ái" },
      { codeProvince: "66", code: "585", name: "Huyện Ninh Sơn" },
      { codeProvince: "66", code: "586", name: "Huyện Ninh Hải" },
      { codeProvince: "66", code: "587", name: "Huyện Ninh Phước" },
      { codeProvince: "66", code: "588", name: "Huyện Thuận Bắc" },
      { codeProvince: "66", code: "589", name: "Huyện Thuận Nam" },

      // Tỉnh Bình Thuận (10 Districts)
      { codeProvince: "80", code: "593", name: "Thành phố Phan Thiết" },
      { codeProvince: "80", code: "594", name: "Thị xã La Gi" },
      { codeProvince: "80", code: "595", name: "Huyện Tuy Phong" },
      { codeProvince: "80", code: "596", name: "Huyện Bắc Bình" },
      { codeProvince: "80", code: "597", name: "Huyện Hàm Thuận Bắc" },
      { codeProvince: "80", code: "598", name: "Huyện Hàm Thuận Nam" },
      { codeProvince: "80", code: "599", name: "Huyện Tánh Linh" },
      { codeProvince: "80", code: "600", name: "Huyện Đức Linh" },
      { codeProvince: "80", code: "601", name: "Huyện Hàm Tân" },
      { codeProvince: "80", code: "602", name: "Huyện Phú Quí" },

      // Tỉnh Kon Tum (10 Districts)
      { codeProvince: "58", code: "608", name: "Thành phố Kon Tum" },
      { codeProvince: "58", code: "610", name: "Huyện Đắk Glei" },
      { codeProvince: "58", code: "611", name: "Huyện Ngọc Hồi" },
      { codeProvince: "58", code: "612", name: "Huyện Đắk Tô" },
      { codeProvince: "58", code: "613", name: "Huyện Kon Plông" },
      { codeProvince: "58", code: "614", name: "Huyện Kon Rẫy" },
      { codeProvince: "58", code: "615", name: "Huyện Đắk Hà" },
      { codeProvince: "58", code: "616", name: "Huyện Sa Thầy" },
      { codeProvince: "58", code: "617", name: "Huyện Tu Mơ Rông" },
      { codeProvince: "58", code: "618", name: "Huyện Ia H' Drai" },

      // Tỉnh Gia Lai (17 Districts)
      { codeProvince: "60", code: "622", name: "Thành phố Pleiku" },
      { codeProvince: "60", code: "623", name: "Thị xã An Khê" },
      { codeProvince: "60", code: "624", name: "Thị xã Ayun Pa" },
      { codeProvince: "60", code: "625", name: "Huyện KBang" },
      { codeProvince: "60", code: "626", name: "Huyện Đăk Đoa" },
      { codeProvince: "60", code: "627", name: "Huyện Chư Păh" },
      { codeProvince: "60", code: "628", name: "Huyện Ia Grai" },
      { codeProvince: "60", code: "629", name: "Huyện Mang Yang" },
      { codeProvince: "60", code: "630", name: "Huyện Kông Chro" },
      { codeProvince: "60", code: "631", name: "Huyện Đức Cơ" },
      { codeProvince: "60", code: "632", name: "Huyện Chư Prông" },
      { codeProvince: "60", code: "633", name: "Huyện Chư Sê" },
      { codeProvince: "60", code: "634", name: "Huyện Đăk Pơ" },
      { codeProvince: "60", code: "635", name: "Huyện Ia Pa" },
      { codeProvince: "60", code: "637", name: "Huyện Krông Pa" },
      { codeProvince: "60", code: "638", name: "Huyện Phú Thiện" },
      { codeProvince: "60", code: "639", name: "Huyện Chư Pưh" },

      // Tỉnh Đắk Lắk (15 Districts)
      { codeProvince: "63", code: "643", name: "Thành phố Buôn Ma Thuột" },
      { codeProvince: "63", code: "644", name: "Thị Xã Buôn Hồ" },
      { codeProvince: "63", code: "645", name: "Huyện Ea H'leo" },
      { codeProvince: "63", code: "646", name: "Huyện Ea Súp" },
      { codeProvince: "63", code: "647", name: "Huyện Buôn Đôn" },
      { codeProvince: "63", code: "648", name: "Huyện Cư M'gar" },
      { codeProvince: "63", code: "649", name: "Huyện Krông Búk" },
      { codeProvince: "63", code: "650", name: "Huyện Krông Năng" },
      { codeProvince: "63", code: "651", name: "Huyện Ea Kar" },
      { codeProvince: "63", code: "652", name: "Huyện M'Đrắk" },
      { codeProvince: "63", code: "653", name: "Huyện Krông Bông" },
      { codeProvince: "63", code: "654", name: "Huyện Krông Pắc" },
      { codeProvince: "63", code: "655", name: "Huyện Krông A Na" },
      { codeProvince: "63", code: "656", name: "Huyện Lắk" },
      { codeProvince: "63", code: "657", name: "Huyện Cư Kuin" },

      // Tỉnh Đắk Nông (8 Districts)
      { codeProvince: "64", code: "660", name: "Thành phố Gia Nghĩa" },
      { codeProvince: "64", code: "661", name: "Huyện Đăk Glong" },
      { codeProvince: "64", code: "662", name: "Huyện Cư Jút" },
      { codeProvince: "64", code: "663", name: "Huyện Đắk Mil" },
      { codeProvince: "64", code: "664", name: "Huyện Krông Nô" },
      { codeProvince: "64", code: "665", name: "Huyện Đắk Song" },
      { codeProvince: "64", code: "666", name: "Huyện Đắk R'Lấp" },
      { codeProvince: "64", code: "667", name: "Huyện Tuy Đức" },

      // Tỉnh Lâm Đồng (12 Districts)
      { codeProvince: "67", code: "672", name: "Thành phố Đà Lạt" },
      { codeProvince: "67", code: "673", name: "Thành phố Bảo Lộc" },
      { codeProvince: "67", code: "674", name: "Huyện Đam Rông" },
      { codeProvince: "67", code: "675", name: "Huyện Lạc Dương" },
      { codeProvince: "67", code: "676", name: "Huyện Lâm Hà" },
      { codeProvince: "67", code: "677", name: "Huyện Đơn Dương" },
      { codeProvince: "67", code: "678", name: "Huyện Đức Trọng" },
      { codeProvince: "67", code: "679", name: "Huyện Di Linh" },
      { codeProvince: "67", code: "680", name: "Huyện Bảo Lâm" },
      { codeProvince: "67", code: "681", name: "Huyện Đạ Huoai" },
      { codeProvince: "67", code: "682", name: "Huyện Đạ Tẻh" },
      { codeProvince: "67", code: "683", name: "Huyện Cát Tiên" },

      // Tỉnh Bình Phước (11 Districts)
      { codeProvince: "83", code: "688", name: "Thị xã Phước Long" },
      { codeProvince: "83", code: "689", name: "Thành phố Đồng Xoài" },
      { codeProvince: "83", code: "690", name: "Thị xã Bình Long" },
      { codeProvince: "83", code: "691", name: "Huyện Bù Gia Mập" },
      { codeProvince: "83", code: "692", name: "Huyện Lộc Ninh" },
      { codeProvince: "83", code: "693", name: "Huyện Bù Đốp" },
      { codeProvince: "83", code: "694", name: "Huyện Hớn Quản" },
      { codeProvince: "83", code: "695", name: "Huyện Đồng Phú" },
      { codeProvince: "83", code: "696", name: "Huyện Bù Đăng" },
      { codeProvince: "83", code: "697", name: "Thị xã Chơn Thành" },
      { codeProvince: "83", code: "698", name: "Huyện Phú Riềng" },

      // Tỉnh Tây Ninh (9 Districts)
      { codeProvince: "84", code: "703", name: "Thành phố Tây Ninh" },
      { codeProvince: "84", code: "705", name: "Huyện Tân Biên" },
      { codeProvince: "84", code: "706", name: "Huyện Tân Châu" },
      { codeProvince: "84", code: "707", name: "Huyện Dương Minh Châu" },
      { codeProvince: "84", code: "708", name: "Huyện Châu Thành" },
      { codeProvince: "84", code: "709", name: "Thị xã Hòa Thành" },
      { codeProvince: "84", code: "710", name: "Huyện Gò Dầu" },
      { codeProvince: "84", code: "711", name: "Huyện Bến Cầu" },
      { codeProvince: "84", code: "712", name: "Thị xã Trảng Bàng" },

      // Tỉnh Bình Dương (9 Districts)
      { codeProvince: "82", code: "718", name: "Thành phố Thủ Dầu Một" },
      { codeProvince: "82", code: "719", name: "Huyện Bàu Bàng" },
      { codeProvince: "82", code: "720", name: "Huyện Dầu Tiếng" },
      { codeProvince: "82", code: "721", name: "Thị xã Bến Cát" },
      { codeProvince: "82", code: "722", name: "Huyện Phú Giáo" },
      { codeProvince: "82", code: "723", name: "Thành phố Tân Uyên" },
      { codeProvince: "82", code: "724", name: "Thành phố Dĩ An" },
      { codeProvince: "82", code: "725", name: "Thành phố Thuận An" },
      { codeProvince: "82", code: "726", name: "Huyện Bắc Tân Uyên" },

      // Tỉnh Đồng Nai (11 Districts)
      { codeProvince: "81", code: "731", name: "Thành phố Biên Hòa" },
      { codeProvince: "81", code: "732", name: "Thành phố Long Khánh" },
      { codeProvince: "81", code: "734", name: "Huyện Tân Phú" },
      { codeProvince: "81", code: "735", name: "Huyện Vĩnh Cửu" },
      { codeProvince: "81", code: "736", name: "Huyện Định Quán" },
      { codeProvince: "81", code: "737", name: "Huyện Trảng Bom" },
      { codeProvince: "81", code: "738", name: "Huyện Thống Nhất" },
      { codeProvince: "81", code: "739", name: "Huyện Cẩm Mỹ" },
      { codeProvince: "81", code: "740", name: "Huyện Long Thành" },
      { codeProvince: "81", code: "741", name: "Huyện Xuân Lộc" },
      { codeProvince: "81", code: "742", name: "Huyện Nhơn Trạch" },

      // Tỉnh Bà Rịa - Vũng Tàu (8 Districts)
      { codeProvince: "79", code: "747", name: "Thành phố Vũng Tàu" },
      { codeProvince: "79", code: "748", name: "Thành phố Bà Rịa" },
      { codeProvince: "79", code: "750", name: "Huyện Châu Đức" },
      { codeProvince: "79", code: "751", name: "Huyện Xuyên Mộc" },
      { codeProvince: "79", code: "752", name: "Huyện Long Điền" },
      { codeProvince: "79", code: "753", name: "Huyện Đất Đỏ" },
      { codeProvince: "79", code: "754", name: "Thị xã Phú Mỹ" },
      { codeProvince: "79", code: "755", name: "Huyện Côn Đảo" },

      // Thành phố Hồ Chí Minh (22 Districts)
      { codeProvince: "70", code: "760", name: "Quận 1" },
      { codeProvince: "70", code: "761", name: "Quận 12" },
      { codeProvince: "70", code: "764", name: "Quận Gò Vấp" },
      { codeProvince: "70", code: "765", name: "Quận Bình Thạnh" },
      { codeProvince: "70", code: "766", name: "Quận Tân Bình" },
      { codeProvince: "70", code: "767", name: "Quận Tân Phú" },
      { codeProvince: "70", code: "768", name: "Quận Phú Nhuận" },
      { codeProvince: "70", code: "769", name: "Thành phố Thủ Đức" },
      { codeProvince: "70", code: "770", name: "Quận 3" },
      { codeProvince: "70", code: "771", name: "Quận 10" },
      { codeProvince: "70", code: "772", name: "Quận 11" },
      { codeProvince: "70", code: "773", name: "Quận 4" },
      { codeProvince: "70", code: "774", name: "Quận 5" },
      { codeProvince: "70", code: "775", name: "Quận 6" },
      { codeProvince: "70", code: "776", name: "Quận 8" },
      { codeProvince: "70", code: "777", name: "Quận Bình Tân" },
      { codeProvince: "70", code: "778", name: "Quận 7" },
      { codeProvince: "70", code: "783", name: "Huyện Củ Chi" },
      { codeProvince: "70", code: "784", name: "Huyện Hóc Môn" },
      { codeProvince: "70", code: "785", name: "Huyện Bình Chánh" },
      { codeProvince: "70", code: "786", name: "Huyện Nhà Bè" },
      { codeProvince: "70", code: "787", name: "Huyện Cần Giờ" },

      // Tỉnh Long An (15 Districts)
      { codeProvince: "85", code: "794", name: "Thành phố Tân An" },
      { codeProvince: "85", code: "795", name: "Thị xã Kiến Tường" },
      { codeProvince: "85", code: "796", name: "Huyện Tân Hưng" },
      { codeProvince: "85", code: "797", name: "Huyện Vĩnh Hưng" },
      { codeProvince: "85", code: "798", name: "Huyện Mộc Hóa" },
      { codeProvince: "85", code: "799", name: "Huyện Tân Thạnh" },
      { codeProvince: "85", code: "800", name: "Huyện Thạnh Hóa" },
      { codeProvince: "85", code: "801", name: "Huyện Đức Huệ" },
      { codeProvince: "85", code: "802", name: "Huyện Đức Hòa" },
      { codeProvince: "85", code: "803", name: "Huyện Bến Lức" },
      { codeProvince: "85", code: "804", name: "Huyện Thủ Thừa" },
      { codeProvince: "85", code: "805", name: "Huyện Tân Trụ" },
      { codeProvince: "85", code: "806", name: "Huyện Cần Đước" },
      { codeProvince: "85", code: "807", name: "Huyện Cần Giuộc" },
      { codeProvince: "85", code: "808", name: "Huyện Châu Thành" },

      // Tỉnh Tiền Giang (11 Districts)
      { codeProvince: "86", code: "815", name: "Thành phố Mỹ Tho" },
      { codeProvince: "86", code: "816", name: "Thị xã Gò Công" },
      { codeProvince: "86", code: "817", name: "Thị xã Cai Lậy" },
      { codeProvince: "86", code: "818", name: "Huyện Tân Phước" },
      { codeProvince: "86", code: "819", name: "Huyện Cái Bè" },
      { codeProvince: "86", code: "820", name: "Huyện Cai Lậy" },
      { codeProvince: "86", code: "821", name: "Huyện Châu Thành" },
      { codeProvince: "86", code: "822", name: "Huyện Chợ Gạo" },
      { codeProvince: "86", code: "823", name: "Huyện Gò Công Tây" },
      { codeProvince: "86", code: "824", name: "Huyện Gò Công Đông" },
      { codeProvince: "86", code: "825", name: "Huyện Tân Phú Đông" },

      // Tỉnh Bến Tre (9 Districts)
      { codeProvince: "93", code: "829", name: "Thành phố Bến Tre" },
      { codeProvince: "93", code: "831", name: "Huyện Châu Thành" },
      { codeProvince: "93", code: "832", name: "Huyện Chợ Lách" },
      { codeProvince: "93", code: "833", name: "Huyện Mỏ Cày Nam" },
      { codeProvince: "93", code: "834", name: "Huyện Giồng Trôm" },
      { codeProvince: "93", code: "835", name: "Huyện Bình Đại" },
      { codeProvince: "93", code: "836", name: "Huyện Ba Tri" },
      { codeProvince: "93", code: "837", name: "Huyện Thạnh Phú" },
      { codeProvince: "93", code: "838", name: "Huyện Mỏ Cày Bắc" },

      // Tỉnh Trà Vinh (9 Districts)
      { codeProvince: "94", code: "842", name: "Thành phố Trà Vinh" },
      { codeProvince: "94", code: "844", name: "Huyện Càng Long" },
      { codeProvince: "94", code: "845", name: "Huyện Cầu Kè" },
      { codeProvince: "94", code: "846", name: "Huyện Tiểu Cần" },
      { codeProvince: "94", code: "847", name: "Huyện Châu Thành" },
      { codeProvince: "94", code: "848", name: "Huyện Cầu Ngang" },
      { codeProvince: "94", code: "849", name: "Huyện Trà Cú" },
      { codeProvince: "94", code: "850", name: "Huyện Duyên Hải" },
      { codeProvince: "94", code: "851", name: "Thị xã Duyên Hải" },

      // Tỉnh Vĩnh Long (8 Districts)
      { codeProvince: "89", code: "855", name: "Thành phố Vĩnh Long" },
      { codeProvince: "89", code: "857", name: "Huyện Long Hồ" },
      { codeProvince: "89", code: "858", name: "Huyện Mang Thít" },
      { codeProvince: "89", code: "859", name: "Huyện  Vũng Liêm" },
      { codeProvince: "89", code: "860", name: "Huyện Tam Bình" },
      { codeProvince: "89", code: "861", name: "Thị xã Bình Minh" },
      { codeProvince: "89", code: "862", name: "Huyện Trà Ôn" },
      { codeProvince: "89", code: "863", name: "Huyện Bình Tân" },

      // Tỉnh Đồng Tháp (12 Districts)
      { codeProvince: "87", code: "866", name: "Thành phố Cao Lãnh" },
      { codeProvince: "87", code: "867", name: "Thành phố Sa Đéc" },
      { codeProvince: "87", code: "868", name: "Thành phố Hồng Ngự" },
      { codeProvince: "87", code: "869", name: "Huyện Tân Hồng" },
      { codeProvince: "87", code: "870", name: "Huyện Hồng Ngự" },
      { codeProvince: "87", code: "871", name: "Huyện Tam Nông" },
      { codeProvince: "87", code: "872", name: "Huyện Tháp Mười" },
      { codeProvince: "87", code: "873", name: "Huyện Cao Lãnh" },
      { codeProvince: "87", code: "874", name: "Huyện Thanh Bình" },
      { codeProvince: "87", code: "875", name: "Huyện Lấp Vò" },
      { codeProvince: "87", code: "876", name: "Huyện Lai Vung" },
      { codeProvince: "87", code: "877", name: "Huyện Châu Thành" },

      // Tỉnh An Giang (11 Districts)
      { codeProvince: "88", code: "883", name: "Thành phố Long Xuyên" },
      { codeProvince: "88", code: "884", name: "Thành phố Châu Đốc" },
      { codeProvince: "88", code: "886", name: "Huyện An Phú" },
      { codeProvince: "88", code: "887", name: "Thị xã Tân Châu" },
      { codeProvince: "88", code: "888", name: "Huyện Phú Tân" },
      { codeProvince: "88", code: "889", name: "Huyện Châu Phú" },
      { codeProvince: "88", code: "890", name: "Thị xã Tịnh Biên" },
      { codeProvince: "88", code: "891", name: "Huyện Tri Tôn" },
      { codeProvince: "88", code: "892", name: "Huyện Châu Thành" },
      { codeProvince: "88", code: "893", name: "Huyện Chợ Mới" },
      { codeProvince: "88", code: "894", name: "Huyện Thoại Sơn" },

      // Tỉnh Kiên Giang (15 Districts)
      { codeProvince: "92", code: "899", name: "Thành phố Rạch Giá" },
      { codeProvince: "92", code: "900", name: "Thành phố Hà Tiên" },
      { codeProvince: "92", code: "902", name: "Huyện Kiên Lương" },
      { codeProvince: "92", code: "903", name: "Huyện Hòn Đất" },
      { codeProvince: "92", code: "904", name: "Huyện Tân Hiệp" },
      { codeProvince: "92", code: "905", name: "Huyện Châu Thành" },
      { codeProvince: "92", code: "906", name: "Huyện Giồng Riềng" },
      { codeProvince: "92", code: "907", name: "Huyện Gò Quao" },
      { codeProvince: "92", code: "908", name: "Huyện An Biên" },
      { codeProvince: "92", code: "909", name: "Huyện An Minh" },
      { codeProvince: "92", code: "910", name: "Huyện Vĩnh Thuận" },
      { codeProvince: "92", code: "911", name: "Thành phố Phú Quốc" },
      { codeProvince: "92", code: "912", name: "Huyện Kiên Hải" },
      { codeProvince: "92", code: "913", name: "Huyện U Minh Thượng" },
      { codeProvince: "92", code: "914", name: "Huyện Giang Thành" },

      // Thành phố Cần Thơ (9 Districts)
      { codeProvince: "90", code: "916", name: "Quận Ninh Kiều" },
      { codeProvince: "90", code: "917", name: "Quận Ô Môn" },
      { codeProvince: "90", code: "918", name: "Quận Bình Thuỷ" },
      { codeProvince: "90", code: "919", name: "Quận Cái Răng" },
      { codeProvince: "90", code: "923", name: "Quận Thốt Nốt" },
      { codeProvince: "90", code: "924", name: "Huyện Vĩnh Thạnh" },
      { codeProvince: "90", code: "925", name: "Huyện Cờ Đỏ" },
      { codeProvince: "90", code: "926", name: "Huyện Phong Điền" },
      { codeProvince: "90", code: "927", name: "Huyện Thới Lai" },

      // Tỉnh Hậu Giang (8 Districts)
      { codeProvince: "91", code: "930", name: "Thành phố Vị Thanh" },
      { codeProvince: "91", code: "931", name: "Thành phố Ngã Bảy" },
      { codeProvince: "91", code: "932", name: "Huyện Châu Thành A" },
      { codeProvince: "91", code: "933", name: "Huyện Châu Thành" },
      { codeProvince: "91", code: "934", name: "Huyện Phụng Hiệp" },
      { codeProvince: "91", code: "935", name: "Huyện Vị Thuỷ" },
      { codeProvince: "91", code: "936", name: "Huyện Long Mỹ" },
      { codeProvince: "91", code: "937", name: "Thị xã Long Mỹ" },

      // Tỉnh Sóc Trăng (11 Districts)
      { codeProvince: "95", code: "941", name: "Thành phố Sóc Trăng" },
      { codeProvince: "95", code: "942", name: "Huyện Châu Thành" },
      { codeProvince: "95", code: "943", name: "Huyện Kế Sách" },
      { codeProvince: "95", code: "944", name: "Huyện Mỹ Tú" },
      { codeProvince: "95", code: "945", name: "Huyện Cù Lao Dung" },
      { codeProvince: "95", code: "946", name: "Huyện Long Phú" },
      { codeProvince: "95", code: "947", name: "Huyện Mỹ Xuyên" },
      { codeProvince: "95", code: "948", name: "Thị xã Ngã Năm" },
      { codeProvince: "95", code: "949", name: "Huyện Thạnh Trị" },
      { codeProvince: "95", code: "950", name: "Thị xã Vĩnh Châu" },
      { codeProvince: "95", code: "951", name: "Huyện Trần Đề" },

      // Tỉnh Bạc Liêu (7 Districts)
      { codeProvince: "96", code: "954", name: "Thành phố Bạc Liêu" },
      { codeProvince: "96", code: "956", name: "Huyện Hồng Dân" },
      { codeProvince: "96", code: "957", name: "Huyện Phước Long" },
      { codeProvince: "96", code: "958", name: "Huyện Vĩnh Lợi" },
      { codeProvince: "96", code: "959", name: "Thị xã Giá Rai" },
      { codeProvince: "96", code: "960", name: "Huyện Đông Hải" },
      { codeProvince: "96", code: "961", name: "Huyện Hoà Bình" },

      // Tỉnh Cà Mau (9 Districts)
      { codeProvince: "97", code: "964", name: "Thành phố Cà Mau" },
      { codeProvince: "97", code: "966", name: "Huyện U Minh" },
      { codeProvince: "97", code: "967", name: "Huyện Thới Bình" },
      { codeProvince: "97", code: "968", name: "Huyện Trần Văn Thời" },
      { codeProvince: "97", code: "969", name: "Huyện Cái Nước" },
      { codeProvince: "97", code: "970", name: "Huyện Đầm Dơi" },
      { codeProvince: "97", code: "971", name: "Huyện Năm Căn" },
      { codeProvince: "97", code: "972", name: "Huyện Phú Tân" },
      { codeProvince: "97", code: "973", name: "Huyện Ngọc Hiển" }
  ];

    for (const data of listData) {
      const dataExists = await repository
        .createQueryBuilder('base')
        .andWhere(`base.code=:code`, { code: data.code })
        .getOne();

      if (!dataExists) {
        let newData = repository.create(data);
        newData = await repository.save(newData);
      }
    }
  }
}