version: '3.9'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - database:/database
    ports:
      - 5432:5432
    restart: always

  cache:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - cache:/data

  server:
   build:
     context: .
     dockerfile: Dockerfile
   container_name: nest-fastify-dev
   ports:
     - '3000:3000'
   depends_on:
     - database
     - cache
   environment:
     REDIS_HOST: 'cache'
     DATABASE_HOST: 'database'
   volumes:
     - server:/app

networks:
  database:
    driver: bridge

volumes:
  database:
  cache:
  server:
