version: '3.9'

services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - database:/database
    ports:
      - 5432:5432
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-q", "-d", "{YOUR_DATABASE_NAME}", "-U", "{YOUR_DATABASE_USERNAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - network

  cache:
    image: redis:latest
    ports:
      - 6379:6379
    volumes:
      - cache:/data
    networks:
      - network

  server:
    build:
      context: .
      args:
        - PROD=true
      dockerfile: Dockerfile
    container_name: nest-fastify
    environment:
      REDIS_HOST: 'cache'
      DATABASE_HOST: 'database'
    ports:
      - '3000:3000'
    depends_on:
      - database
      - cache
    volumes:
      - server:/app
    networks:
      - network

networks:
  network:
    driver: bridge
    name: network

volumes:
  database:
  cache:
  server:
