import { API, testCase } from './index';

import {
  P_DATA_TYPE_LISTED,
  P_DATA_TYPE_CREATE,
  P_DATA_TYPE_UPDATE,
  P_DATA_TYPE_DELETE,
  P_DATA_LISTED,
  P_DATA_CREATE,
  P_DATA_UPDATE,
  P_DATA_DELETE,
  P_SUB_ORGANIZATION_CREATE,
  P_SUB_ORGANIZATION_UPDATE,
  P_SUB_ORGANIZATION_UPDATE_ACTIVE_STATUS,
  P_SUB_ORGANIZATION_DELETE,
} from '@service';

describe('Role -' +  API, () =>
  testCase('Role', [
    P_DATA_TYPE_LISTED,
    P_DATA_TYPE_CREATE,
    P_DATA_TYPE_UPDATE,
    P_DATA_TYPE_DELETE,
    P_DATA_LISTED,
    P_DATA_CREATE,
    P_DATA_UPDATE,
    P_DATA_DELETE,
    P_SUB_ORGANIZATION_CREATE,
    P_SUB_ORGANIZATION_UPDATE,
    P_SUB_ORGANIZATION_UPDATE_ACTIVE_STATUS,
    P_SUB_ORGANIZATION_DELETE
  ]));
