export enum E_APPROVE_STATUS {
    WAITING_APPROVED = 'WAITING_APPROVE',
    APPROVED = 'APPROVED',
    REJECTED = 'REJECTED',
    STOP_SELLING = 'STOP_SELLING',
    CANCELLED = 'CANCELLED',
    ALL = 'ALL'
}
